;;(function(){mqaddr={version:'4.7.0',status:0,idx:0,AddressFcgiURL:'//open.mqwallet.qq.com/cgi-bin/WalletAddress.fcgi',AddressFcgiURL_v2:'//proxy.vac.qq.com/cgi-bin/srfentry.fcgi',appInfo:{0:[{name:'钱包常驻',url:'//i.qianbao.qq.com/profile/address/list.html',surl:'//i.qianbao.qq.com/profile/address/sync_addr.html',domain:"*.qq.com"}],100273020:[{name:'京东',url:'http://mm.wanggou.com/',surl:'http://mm.wanggou.com/m/mqaddr/sync_addr.html',domain:"mm.wanggou.com"},{name:'京东',url:'http://wq.jd.com/',surl:'http://wq.jd.com/m/mqaddr/sync_addr.html',domain:"wq.jd.com"},{name:'京东',url:'http://wqs.jd.com/',surl:'http://wqs.jd.com/m/mqaddr/sync_addr.html',domain:"wqs.jd.com"}],210915:[{name:'美丽说',url:'http://m.meilishuo.com/',surl:'http://m.meilishuo.com/sq/sync_addr',domain:"m.meilishuo.com"}],3:[{name:'拍拍',url:'http://www.paipai.com/',surl:'http://m.paipai.com/m2/p/cart/order/sync_addr.html',domain:"*.paipai.com"}],1101690349:[{name:'拍拍',url:'http://www.paipai.com/',surl:'http://m.paipai.com/m2/p/cart/order/sync_addr.html',domain:"*.paipai.com"}],101177501:[{name:'同程',url:'http://wx.17u.cn/qqtrain/',surl:'http://wx.17u.cn/qqtrain/sync_addr.html',domain:"*.17u.cn"}],201293:[{name:'蘑菇街',url:'http://m.mogujie.com/x6/order/init',surl:'',domain:"m.mogujie.com"}],101233410:[{name:"微票",url:"http://store.wepiao.com/index.php/wap/order-submit.html",surl:"http://store.wepiao.com/public/skins/html/sync_addr.html",domain:"wepiao.com"}]},getUin:function(callback){var self=this;if(self._uin){callback&&callback(self._uin);return;};mqq.data.getUserInfo(function(result){self._uin=result.uin;callback&&callback(self._uin);});},setIdx:function(idx){this.idx=idx||0;},getAppInfo:function(id){var d=mqaddr.appInfo[id];if(d==null)return null;if(d.length==undefined){return d;}
return mqaddr.appInfo[id][this.idx]||mqaddr.appInfo[id][0]||null;},call:function(opt){var url='//i.qianbao.qq.com/profile/address/choose.html';this.status=1;mqaddr.url.open(url,{_wv:1,aid:opt.aid||0,idx:opt.idx||0,appid:opt.appid||0});},url:{unserialParams:function(paramstr){paramstr=paramstr||location.search.substring(1);var params=paramstr.split("&"),paramMap={},param;$.each(params,function(index,param){param=param.split(/=/);paramMap[param[0]]=(param[1]||"");});return paramMap},get:function(name,url){if(!url&&!this.paramsMap){this.paramsMap=this.unserialParams()}else{if(url){var index=url.indexOf("?");return this.unserialParams(index!==-1?url.substr(index+1):url)[name]}}
return name?this.paramsMap[name]:this.paramsMap},appendParams:function(params,url){if(!params){return url}
url=url||location.href;params=$.param(params);if(url.indexOf("?")!=-1){if(url.lastIndexOf("&")!=url.length-1){url+="&"}
url+=params}else{url+="?"+params}
return url;},replaceParams:function(param,value,url){var oldValue=mqaddr.url.get(param),pattern=eval('/('+param+'=)([^&]*)/gi');var retUrl=url.replace(pattern,param+'='+value);return retUrl;},open:function(url,params,hash){var self=this;if(!!params){url=self.appendParams(params,url);}
if(!!hash){url+='#'+hash;}
mqq.ui.openUrl({url:url,target:1,style:1});},replace:function(url,params){var self=this;if(!!params){url=self.appendParams(params,url);}
window.location.replace(url);}},data:{listen:function(callback){if(mqq.QQVersion<'5.0'){var self=this;document.addEventListener("qbrowserVisibilityChange",function(e){if(!e.hidden){var data={type:1,choose:self.status&&mqaddr.storage.getCookie('mqaddr')};self.status=0;callback&&callback(data);}});}
else{mqq.addEventListener("mqqAddrSync",function(data,source){data.type=2;callback&&callback(data,source);});}},readData:function(callback){var result=mqaddr.storage.getCookie('mqaddr');callback&&callback(result);},getAddress:function(callback){mqaddr.net.srfSend({params:{data:{'10665':{}}},success:function(data){var addrs=data.stGetAddressRsp.stUserAddr.vAddrs,defaultId=data.stGetAddressRsp.stUserAddr.iDefAid,appload=data.stGetAddressRsp.AppLoad;if(typeof appload=='object'){var isEmpty=true;for(var i in appload){isEmpty=false;break;}
if(isEmpty){appload=false;}}
var ret={addrs:addrs,defaultId:defaultId,apps:appload,ecode:0}
callback&&callback(ret);},fail:function(ret){mqaddr.net.srfFailHandler(ret);}})},getAddressById:function(id,callback){mqaddr.net.srfSend({params:{data:{'10671':{'addressid':parseInt(id,10),'bDefault':true}}},success:function(resp){var data=resp.data;callback&&callback(data);},fail:function(ret){mqaddr.net.srfFailHandler(ret);}})},setDefaultAddress:function(id,callback){mqaddr.net.srfSend({params:{data:{'10680':{'addressid':parseInt(id,10),'bDefault':true}}},success:function(resp){callback&&callback(resp);},fail:function(ret){mqaddr.net.srfFailHandler(ret);}})},getDefaultAddress:function(callback){mqaddr.net.getAddressById(0,callback);},getSelectAddress:function(callback){mqaddr.net.srfSend({params:{data:{'10671':{'addressid':parseInt(id,10),'bDefault':false}}},success:function(resp){var data=resp.data;callback&&callback(data);},fail:function(ret){mqaddr.net.srfFailHandler(ret);}})},setSelectAddress:function(id,callback){mqaddr.net.srfSend({params:{data:{'10680':{'addressid':parseInt(id,10),'bDefault':false}}},success:function(resp){callback&&callback(resp);},fail:function(ret){mqaddr.net.srfFailHandler(ret);}})},addAddress:function(data,callback){data.cityCode=parseInt(data.cityCode,10);data.zipCode=parseInt(data.zipCode,10);mqaddr.net.srfSend({params:{'data':{'10668':{'data':data}}},success:function(resp){var ret={data:{addAddress:{retBody:{addressid:resp.addressid}}}}
callback&&callback(ret);},fail:function(ret){mqaddr.net.srfFailHandler(ret);}})},deleteAddress:function(id,callback){mqaddr.net.srfSend({params:{data:{'10683':{vecAid:[parseInt(id,10)]}}},success:function(data){callback&&callback({ret:0});},fail:function(ret){mqaddr.net.srfFailHandler(ret);}})},updateAddress:function(id,data,callback){data.addressid=id;data.cityCode=parseInt(data.cityCode,10);data.zipCode=parseInt(data.zipCode,10);mqaddr.net.srfSend({params:{'data':{'10670':{'data':data}}},success:function(resp){console.log('-->resp');callback&&callback();},fail:function(ret){mqaddr.net.srfFailHandler(ret);}})},getDistrict:function(code){var p=code-code%10000,c=code-code%100,t=code;var muni=Math.floor(p/10000);if(muni==11||muni==12||muni==31||muni==50){c=t;t=-1;}
if(!p||p=='-1'||!c||c=='-1'){return'';}
var _rd=bbc_district_data;if(_rd[p]){if(typeof(_rd[p][1])=="object"){if(!t||t=='-1'){if(typeof(_rd[p][1][c])=="object"){return _rd[p][0]+_rd[p][1][c][0];}
return _rd[p][0]+_rd[p][1][c];}
if(typeof(_rd[p][1][c])!="object"){return _rd[p][0]+(_rd[p][1][c]||'');}
if(typeof(_rd[p][1][c][1][t])=="object"){return _rd[p][0]+_rd[p][1][c][0]+_rd[p][1][c][1][t][0];}
else{return _rd[p][0]+_rd[p][1][c][0]+(_rd[p][1][c][1][t]||'');}}
return _rd[p][0];}
return'';},dcReport:function(page_mode,oper_pra1,oper_pra2){mqaddr.getUin(function(uin){mqq.device.getDeviceInfo(function(data){var params='',platform=data.systemName;params='uin='+uin
+'&platform='+platform
+'&page_mode='+page_mode
+'&oper_pra1='+oper_pra1;if(!!oper_pra2){params+='&oper_pra2='+oper_pra2;}
mqq.data.pbReport('10003',params);});});}},ui:{show:function(text){mqq.ui.showTips({text:text});},setActBtn:function(param,callback){mqq.ui.setActionButton(param,callback);},open:function(url,params,target){if(!!params){url=mqaddr.url.appendParams(params,url);}
if(!!target){url+='#'+target;}
mqq.ui.openUrl({url:url,target:1,style:3});}},storage:{getCookie:function(name){if(document.cookie&&document.cookie!=''){var cookieArr=document.cookie.split('; ');for(var i=0,cl=cookieArr.length,name=encodeURIComponent(name),tmpArr;i<cl;i++){tmpArr=cookieArr[i].split('=');if(name==tmpArr[0]){return decodeURIComponent(tmpArr[1]||'');}}}
return'';}},net:{getMenShenToken:function(){var hash=5381;var str=mqaddr.storage.getCookie("skey");for(var i=0,len=str.length;i<len;++i)
{hash+=(hash<<5)+str.charCodeAt(i);}
return hash&0x7fffffff;},srfSend:function(param){if(typeof SRF=='undefined'){alert('页面需要引入必要的配置');return;}
SRF.request(param);},srfFailHandler:function(){alert('数据加载失败，请稍后再试');},send:function(url,data,callback){data.g_tk=mqaddr.net.getMenShenToken();$.ajax({url:url,data:data,dataType:'json',beforeSend:function(xhr){xhr.withCredentials=true;},success:function(json){callback&&callback(json);},error:function(json){}});},loadAddrData:function(callback){if(!window['bbc.districtdata.js']){mqaddr.net.loadScript('//static.paipaiimg.com/js/mobile/bbc.districtdata.js?v=1.0.4',function(){callback();},"utf-8");}
else{callback();}},loadScript:function(url,callback,charset){if(typeof callback=="string"){charset=callback;callback=function(){};}
var sc=document.createElement("script"),head=document.getElementsByTagName("head")[0];sc.setAttribute("charset",charset||"utf-8");sc.src=url;sc.onload=function(){callback&&callback();head.removeChild(sc);};head.appendChild(sc);}},util:{speed:function(point,pageFlag){if(!pageFlag){return false;}
var performanceList=(function(){if(typeof window.performance!='undefined'){try{var navigationTime=window.performance.timing;var field=["navigationStart","unloadEventStart","unloadEventEnd","redirectStart","redirectEnd","fetchStart","domainLookupStart","domainLookupEnd","connectStart","connectEnd","requestStart","responseStart","responseEnd","domLoading","domInteractive","domContentLoadedEventStart","domContentLoadedEventEnd","domComplete","loadEventStart","loadEventEnd"];var startTime=navigationTime.navigationStart;var timeList={};for(var i=1,j=field.length;i<j;i++){if(typeof navigationTime[field[i]]!='undefined'&&navigationTime[field[i]]>0){var timeMs=navigationTime[field[i]]-startTime;if(timeMs>0&&timeMs<100000){timeList[i]=timeMs;continue;}}
timeList[i]=0;}
return timeList;}catch(e){return null;}}else{return null;}})();if(performanceList==null){performanceList={};for(var i=1;i<=19;i++){performanceList[i]=0;}}
point=$.extend(performanceList,point);mqaddr.util.delay(500,function(){var i=new Image();i.src='//isdspeed.qq.com/cgi-bin/r.cgi?'+$.param($.extend(point,{flag1:169,flag2:2172,flag3:pageFlag}));});},delay:function(ts,cb){if(!ts)return cb();return setTimeout(function(){cb();},ts);},report:function(pageFlag,point){var onloadFn=window.onload;window.onload=function(){if(typeof onloadFn=="function"){onloadFn();}
mqaddr.util.speed(point||{},pageFlag);mqaddr.net.loadScript("//pingjs.qq.com/ping.js",function(){if(typeof pgvMain=='function'){pgvMain();}});};}}};})();